["OPENAI_API_KEY"]
OPENAI_API_KEY = "your_openai_api_key"

from huggingface_hub import login
import streamlit as st

# Authenticate using the Hugging Face token from secrets
login(token=st.secrets["HF_TOKEN"])
