import openai
from huggingface_hub import login
import streamlit as st

# Access secrets from Streamlit's secrets management
openai.api_key = st.secrets["OPENAI_API_KEY"]

# Authenticate with Hugging Face using the token from secrets
login(token=st.secrets["HF_TOKEN"])
